version: '3.8'

services:
  grammar-llm:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - grammar_llm_models:/root/.cache/huggingface/hub
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  grammar_llm_models:
