import { jsPDF } from 'jspdf';
import type { Suggestion } from '../../electron/core/types';

// WCAG 2.0 AA compliant colors on white background (contrast >= 4.5:1)
const COLOR_TITLE = [41, 41, 41] as const;
const COLOR_BODY = [51, 51, 51] as const;
const COLOR_ERROR = [163, 28, 28] as const;
const COLOR_CORRECT = [21, 111, 56] as const;
const COLOR_LABEL = [80, 80, 80] as const;
const COLOR_LINE = [180, 180, 180] as const;
const COLOR_SCORE = [21, 111, 56] as const;
const COLOR_BG_ORIG = [254, 226, 226] as const;
const COLOR_BG_CORR = [220, 252, 231] as const;

interface Token {
  text: string;
  highlighted: boolean;
}

function parseHighlightedTokens(html: string, spanClass: string): Token[] {
  if (!html) return [{ text: '', highlighted: false }];
  const tokens: Token[] = [];
  const regex = new RegExp(`<span class="${spanClass.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}">([^<]*)</span>`, 'g');
  let lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = regex.exec(html)) !== null) {
    if (match.index > lastIndex) {
      tokens.push({ text: html.substring(lastIndex, match.index), highlighted: false });
    }
    tokens.push({ text: match[1], highlighted: true });
    lastIndex = regex.lastIndex;
  }
  if (lastIndex < html.length) {
    tokens.push({ text: html.substring(lastIndex), highlighted: false });
  }
  tokens.forEach((t) => { t.text = t.text.replace(/<[^>]*>/g, ''); });
  return tokens;
}

export function generatePdfReport(suggestions: Suggestion[], score: number | null): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const marginL = 20;
  const marginR = 20;
  const usableW = pageW - marginL - marginR;
  let y = 20;

  const checkPage = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - 15) {
      doc.addPage();
      y = 20;
    }
  };

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...COLOR_TITLE);
  doc.text('Writing Quality Report', pageW / 2, y, { align: 'center' });
  y += 10;

  doc.setDrawColor(102, 126, 234);
  doc.setLineWidth(0.8);
  doc.line(marginL, y, pageW - marginR, y);
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(...COLOR_BODY);
  doc.text('Writing Quality Score:', marginL, y);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...COLOR_SCORE);
  doc.text(`${score ?? '—'} / 100`, marginL + 58, y);
  y += 12;

  doc.setDrawColor(...COLOR_LINE);
  doc.setLineWidth(0.3);
  doc.line(marginL, y, pageW - marginR, y);
  y += 8;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...COLOR_TITLE);
  doc.text('Suggestions', marginL, y);
  y += 8;

  if (suggestions.length === 0) {
    checkPage(10);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(12);
    doc.setTextColor(...COLOR_BODY);
    doc.text('No grammar issues found. Great writing!', marginL, y);
    y += 10;
  } else {
    suggestions.forEach((s, i) => {
      checkPage(40);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(...COLOR_TITLE);
      doc.text(`${i + 1}. ${s.sentence}`, marginL, y);
      y += 7;

      y = renderHighlightedRow(
        doc, 'Original:',
        parseHighlightedTokens(s.original_highlighted || s.original, 'error-word'),
        marginL, y, usableW, COLOR_LABEL, COLOR_BODY, COLOR_ERROR, COLOR_BG_ORIG,
      );
      y += 2;
      y = renderHighlightedRow(
        doc, 'Suggested:',
        parseHighlightedTokens(s.corrected_highlighted || s.corrected, 'corrected-word'),
        marginL, y, usableW, COLOR_LABEL, COLOR_BODY, COLOR_CORRECT, COLOR_BG_CORR,
      );
      y += 6;

      if (i < suggestions.length - 1) {
        doc.setDrawColor(...COLOR_LINE);
        doc.setLineWidth(0.15);
        doc.line(marginL + 5, y, pageW - marginR - 5, y);
        y += 6;
      }
    });
  }

  checkPage(16);
  y += 4;
  doc.setDrawColor(102, 126, 234);
  doc.setLineWidth(0.5);
  doc.line(marginL, y, pageW - marginR, y);
  y += 6;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(...COLOR_LABEL);
  doc.text('Generated by GrammarLLM', pageW / 2, y, { align: 'center' });

  doc.save('writing-quality-report.pdf');
}

function renderHighlightedRow(
  doc: jsPDF,
  label: string,
  tokens: Token[],
  marginL: number,
  y: number,
  usableW: number,
  colorLabel: readonly [number, number, number],
  colorNormal: readonly [number, number, number],
  colorHighlight: readonly [number, number, number],
  bgColor: readonly [number, number, number],
): number {
  const fontSize = 11;
  const lineH = 5.5;
  const labelW = 24;
  const contentX = marginL + labelW;
  const contentW = usableW - labelW;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(fontSize);
  doc.setTextColor(...colorLabel);
  doc.text(label, marginL + 2, y);

  const pieces: Array<{ text: string; highlighted: boolean; width: number }> = [];
  tokens.forEach((tok) => {
    tok.text.split(/( )/).forEach((part) => {
      if (part.length > 0) {
        doc.setFont('helvetica', tok.highlighted ? 'bold' : 'normal');
        pieces.push({ text: part, highlighted: tok.highlighted, width: doc.getTextWidth(part) });
      }
    });
  });

  let curX = contentX;
  let lineY = y;

  pieces.forEach((p) => {
    if (curX + p.width > contentX + contentW && p.text.trim() !== '') {
      lineY += lineH;
      curX = contentX;
      if (lineY > doc.internal.pageSize.getHeight() - 15) {
        doc.addPage();
        lineY = 20;
      }
    }
    if (p.highlighted) {
      doc.setFillColor(...bgColor);
      doc.roundedRect(curX - 0.5, lineY - 3.5, p.width + 1, lineH, 0.8, 0.8, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...colorHighlight);
      doc.text(p.text, curX, lineY);
      doc.setFont('helvetica', 'normal');
    } else {
      doc.setTextColor(...colorNormal);
      doc.text(p.text, curX, lineY);
    }
    curX += p.width;
  });

  return lineY + lineH;
}
